
variable "iso_checksum" {
  type    = string
  default = "8059A99B8902906A90AFE068AC00465C52588C2BD54F5D9D96C1297F88EF1076"
}

variable "iso_checksum_type" {
  type    = string
  default = "sha256"
}

variable "iso_url" {
  type    = string
  default = "./setups/windows11.iso"
}

variable "vm_name" {
  type    = string
  default = "Windows11"
}

source "hyperv-iso" "autogenerated_1" {
  boot_command      = ["<tab> autounattend=http://{{ .HTTPIP }}:{{ .HTTPPort }}/autounattend.xml<enter><wait>"]
  boot_wait         = "2m"
  communicator      = "winrm"
  cpus              = 2
  disk_size         = 61440
  floppy_files      = ["http/autounattend.xml"]
  http_directory    = "http"
  iso_checksum      = "${var.iso_checksum}"
  iso_url           = "${var.iso_url}"
  memory            = 4096
  shutdown_command  = "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\""
  shutdown_timeout  = "30m"
  switch_name       = "Default Switch"
  vm_name           = "${var.vm_name}"
  winrm_password    = "vagrant"
  winrm_timeout     = "6m"
  winrm_username    = "vagrant"
}

build {
  sources = ["source.hyperv-iso.autogenerated_1"]

  provisioner "powershell" {
    scripts = ["scripts/setup.ps1"]
  }

}
