
variable "iso_checksum" {
  type    = string
  default = "8059A99B8902906A90AFE068AC00465C52588C2BD54F5D9D96C1297F88EF1076"
}

variable "iso_checksum_type" {
  type    = string
  default = "sha256"
}

variable "iso_url" {
  type    = string
  default = "./setups/windows11.iso"
}

variable "vm_name" {
  type    = string
  default = "Windows11"
}

source "vmware-iso" "autogenerated_1" {
  iso_checksum      = "${var.iso_checksum}"
  iso_url           = "${var.iso_url}"
  firmware          = "efi-secure"
  cpus              = 1
  memory            = 4096
  network           = "nat"
  core              = 4
  disk_size         = 60000
  vm_name           = "${var.vm_name}"
  cd_files = ["./http/autounattend.xml"]
  cd_label = "autounattend"


}

packer {
  required_plugins {
    vmware = {
      version = "~> 1"
      source = "github.com/hashicorp/vmware"
    }
  }
}

build {
  sources = ["source.hyperv-iso.autogenerated_1"]

  provisioner "powershell" {
    scripts = ["scripts/setup.ps1"]
  }
}
