packer {
  required_plugins {
    vagrant = {
      source  = "github.com/hashicorp/vagrant"
      version = "~> 1"
    }
  }
}

source "hyperv-iso" "autogenerated_1" {
  boot_command         = ["a<wait>a<wait>a"]
  boot_wait            = "0s"
  communicator         = "winrm"
  cpus                 = 4
  disk_size            = 61440
  enable_secure_boot   = true
  generation           = 2
  http_directory       = "./windows/common/http/"
  iso_checksum         = "md5:458ff91f8abc21b75cb544744bf92e6a"
  iso_url              = "http://download.microsoft.com/download/6/2/A/62A76ABB-9990-4EFC-A4FE-C7D698DAEB96/9600.16384.WINBLUE_RTM.130821-1623_X64FRE_SERVER_EVAL_EN-US-IRM_SSS_X64FREE_EN-US_DV5.ISO"
  memory               = 4096
  secondary_iso_images = ["./windows/windows-2012R2-serverdatacenter-amd64/answer.iso"]
  shutdown_command     = "f:\\run-sysprep.cmd"
  switch_name          = "LAN"
  vm_name              = "windows2012r2"
  winrm_password       = "vagrant"
  winrm_timeout        = "4h"
  winrm_username       = "vagrant"
}

build {
  sources = ["source.hyperv-iso.autogenerated_1"]

  provisioner "powershell" {
    elevated_password = "vagrant"
    elevated_user     = "vagrant"
    scripts           = ["./windows/common/install-7zip.ps1", "./windows/common/install-chef.ps1", "./windows/common/compile-dotnet-assemblies.ps1", "./windows/common/cleanup.ps1", "./windows/common/ultradefrag.ps1", "./windows/common/sdelete.ps1"]
  }

  post-processor "vagrant" {
    keep_input_artifact = false
    output              = "{{ .Provider }}_windows-2012r2_chef.box"
  }
}
